version: '3.8'

services:
  couchdb:
    image: couchdb:3.2.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - "5985:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data

  app:
    build: .
    depends_on:
      - couchdb
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./static/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  couchdb_data: